# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: zss_kickparam.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='zss_kickparam.proto',
  package='ZSS.Protocol',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x13zss_kickparam.proto\x12\x0cZSS.Protocol\"\x8b\x01\n\x0bRobot_Param\x12\"\n\x05robot\x18\x01 \x02(\x0b\x32\x13.ZSS.Protocol.Robot\x12+\n\tchipparam\x18\x02 \x02(\x0b\x32\x18.ZSS.Protocol.Chip_Param\x12+\n\tflatparam\x18\x03 \x02(\x0b\x32\x18.ZSS.Protocol.Flat_Param\"L\n\nFlat_Param\x12\n\n\x02\x66\x61\x18\x01 \x02(\x01\x12\n\n\x02\x66\x62\x18\x02 \x02(\x01\x12\n\n\x02\x66\x63\x18\x03 \x02(\x01\x12\x0c\n\x04\x66max\x18\x04 \x02(\x01\x12\x0c\n\x04\x66min\x18\x05 \x02(\x01\"L\n\nChip_Param\x12\n\n\x02\x63\x61\x18\x01 \x02(\x01\x12\n\n\x02\x63\x62\x18\x02 \x02(\x01\x12\n\n\x02\x63\x63\x18\x03 \x02(\x01\x12\x0c\n\x04\x63max\x18\x04 \x02(\x01\x12\x0c\n\x04\x63min\x18\x05 \x02(\x01\"!\n\x05Robot\x12\x0c\n\x04team\x18\x01 \x02(\x05\x12\n\n\x02id\x18\x02 \x02(\x05'
)




_ROBOT_PARAM = _descriptor.Descriptor(
  name='Robot_Param',
  full_name='ZSS.Protocol.Robot_Param',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='robot', full_name='ZSS.Protocol.Robot_Param.robot', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='chipparam', full_name='ZSS.Protocol.Robot_Param.chipparam', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='flatparam', full_name='ZSS.Protocol.Robot_Param.flatparam', index=2,
      number=3, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=38,
  serialized_end=177,
)


_FLAT_PARAM = _descriptor.Descriptor(
  name='Flat_Param',
  full_name='ZSS.Protocol.Flat_Param',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='fa', full_name='ZSS.Protocol.Flat_Param.fa', index=0,
      number=1, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='fb', full_name='ZSS.Protocol.Flat_Param.fb', index=1,
      number=2, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='fc', full_name='ZSS.Protocol.Flat_Param.fc', index=2,
      number=3, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='fmax', full_name='ZSS.Protocol.Flat_Param.fmax', index=3,
      number=4, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='fmin', full_name='ZSS.Protocol.Flat_Param.fmin', index=4,
      number=5, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=179,
  serialized_end=255,
)


_CHIP_PARAM = _descriptor.Descriptor(
  name='Chip_Param',
  full_name='ZSS.Protocol.Chip_Param',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ca', full_name='ZSS.Protocol.Chip_Param.ca', index=0,
      number=1, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='cb', full_name='ZSS.Protocol.Chip_Param.cb', index=1,
      number=2, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='cc', full_name='ZSS.Protocol.Chip_Param.cc', index=2,
      number=3, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='cmax', full_name='ZSS.Protocol.Chip_Param.cmax', index=3,
      number=4, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='cmin', full_name='ZSS.Protocol.Chip_Param.cmin', index=4,
      number=5, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=257,
  serialized_end=333,
)


_ROBOT = _descriptor.Descriptor(
  name='Robot',
  full_name='ZSS.Protocol.Robot',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='team', full_name='ZSS.Protocol.Robot.team', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='id', full_name='ZSS.Protocol.Robot.id', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=335,
  serialized_end=368,
)

_ROBOT_PARAM.fields_by_name['robot'].message_type = _ROBOT
_ROBOT_PARAM.fields_by_name['chipparam'].message_type = _CHIP_PARAM
_ROBOT_PARAM.fields_by_name['flatparam'].message_type = _FLAT_PARAM
DESCRIPTOR.message_types_by_name['Robot_Param'] = _ROBOT_PARAM
DESCRIPTOR.message_types_by_name['Flat_Param'] = _FLAT_PARAM
DESCRIPTOR.message_types_by_name['Chip_Param'] = _CHIP_PARAM
DESCRIPTOR.message_types_by_name['Robot'] = _ROBOT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Robot_Param = _reflection.GeneratedProtocolMessageType('Robot_Param', (_message.Message,), {
  'DESCRIPTOR' : _ROBOT_PARAM,
  '__module__' : 'zss_kickparam_pb2'
  # @@protoc_insertion_point(class_scope:ZSS.Protocol.Robot_Param)
  })
_sym_db.RegisterMessage(Robot_Param)

Flat_Param = _reflection.GeneratedProtocolMessageType('Flat_Param', (_message.Message,), {
  'DESCRIPTOR' : _FLAT_PARAM,
  '__module__' : 'zss_kickparam_pb2'
  # @@protoc_insertion_point(class_scope:ZSS.Protocol.Flat_Param)
  })
_sym_db.RegisterMessage(Flat_Param)

Chip_Param = _reflection.GeneratedProtocolMessageType('Chip_Param', (_message.Message,), {
  'DESCRIPTOR' : _CHIP_PARAM,
  '__module__' : 'zss_kickparam_pb2'
  # @@protoc_insertion_point(class_scope:ZSS.Protocol.Chip_Param)
  })
_sym_db.RegisterMessage(Chip_Param)

Robot = _reflection.GeneratedProtocolMessageType('Robot', (_message.Message,), {
  'DESCRIPTOR' : _ROBOT,
  '__module__' : 'zss_kickparam_pb2'
  # @@protoc_insertion_point(class_scope:ZSS.Protocol.Robot)
  })
_sym_db.RegisterMessage(Robot)


# @@protoc_insertion_point(module_scope)
