# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: zss_rec.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import zss_debug_pb2 as zss__debug__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='zss_rec.proto',
  package='ZSS.Protocol',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rzss_rec.proto\x12\x0cZSS.Protocol\x1a\x0fzss_debug.proto\"8\n\x0bRecMessages\x12)\n\x07recMsgs\x18\x01 \x03(\x0b\x32\x18.ZSS.Protocol.RecMessage\"\xe3\x01\n\nRecMessage\x12\r\n\x05\x63trlC\x18\x01 \x02(\x08\x12\x30\n\x0cselectedArea\x18\x02 \x02(\x0b\x32\x1a.ZSS.Protocol.SelectedArea\x12\x34\n\x0emaintainVision\x18\x03 \x02(\x0b\x32\x1c.ZSS.Protocol.MaintainVision\x12+\n\tdebugMsgs\x18\x04 \x03(\x0b\x32\x18.ZSS.Protocol.Debug_Msgs\x12\x31\n\x0f\x61thenaDebugMsgs\x18\x05 \x01(\x0b\x32\x18.ZSS.Protocol.Debug_Msgs\"F\n\x0cSelectedArea\x12\x0c\n\x04maxX\x18\x01 \x02(\x02\x12\x0c\n\x04maxY\x18\x02 \x02(\x02\x12\x0c\n\x04minX\x18\x03 \x02(\x02\x12\x0c\n\x04minY\x18\x04 \x02(\x02\"\xc0\x01\n\x0eMaintainVision\x12\x11\n\tlastTouch\x18\x01 \x02(\x05\x12\x15\n\rlastTouchTeam\x18\x02 \x02(\x05\x12.\n\nprocessMsg\x18\x03 \x03(\x0b\x32\x1a.ZSS.Protocol.TeamRobotMsg\x12,\n\x08maintain\x18\x04 \x03(\x0b\x32\x1a.ZSS.Protocol.TeamRobotMsg\x12&\n\x05\x62\x61lls\x18\x05 \x02(\x0b\x32\x17.ZSS.Protocol.Balls4Rec\"6\n\x0cTeamRobotMsg\x12&\n\x05robot\x18\x01 \x03(\x0b\x32\x17.ZSS.Protocol.Robot4Rec\"\xa1\x01\n\tRobot4Rec\x12\x0c\n\x04posX\x18\x01 \x02(\x01\x12\x0c\n\x04posY\x18\x02 \x02(\x01\x12\r\n\x05\x61ngle\x18\x03 \x02(\x01\x12\r\n\x05valid\x18\x04 \x02(\x08\x12\x0e\n\x06imuDir\x18\x05 \x02(\x01\x12\x12\n\nimucleaned\x18\x06 \x02(\x08\x12\x0f\n\x07\x62\x61ttery\x18\x07 \x02(\x01\x12\x13\n\x0b\x63\x61pacitance\x18\x08 \x02(\x01\x12\x10\n\x08infrared\x18\t \x01(\x08\"K\n\tBalls4Rec\x12\x0c\n\x04size\x18\x01 \x02(\x05\x12!\n\x04\x62\x61ll\x18\x02 \x03(\x0b\x32\x13.ZSS.Protocol.Point\x12\r\n\x05valid\x18\x03 \x02(\x08'
  ,
  dependencies=[zss__debug__pb2.DESCRIPTOR,])




_RECMESSAGES = _descriptor.Descriptor(
  name='RecMessages',
  full_name='ZSS.Protocol.RecMessages',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='recMsgs', full_name='ZSS.Protocol.RecMessages.recMsgs', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=48,
  serialized_end=104,
)


_RECMESSAGE = _descriptor.Descriptor(
  name='RecMessage',
  full_name='ZSS.Protocol.RecMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ctrlC', full_name='ZSS.Protocol.RecMessage.ctrlC', index=0,
      number=1, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='selectedArea', full_name='ZSS.Protocol.RecMessage.selectedArea', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='maintainVision', full_name='ZSS.Protocol.RecMessage.maintainVision', index=2,
      number=3, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='debugMsgs', full_name='ZSS.Protocol.RecMessage.debugMsgs', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='athenaDebugMsgs', full_name='ZSS.Protocol.RecMessage.athenaDebugMsgs', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=107,
  serialized_end=334,
)


_SELECTEDAREA = _descriptor.Descriptor(
  name='SelectedArea',
  full_name='ZSS.Protocol.SelectedArea',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='maxX', full_name='ZSS.Protocol.SelectedArea.maxX', index=0,
      number=1, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='maxY', full_name='ZSS.Protocol.SelectedArea.maxY', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='minX', full_name='ZSS.Protocol.SelectedArea.minX', index=2,
      number=3, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='minY', full_name='ZSS.Protocol.SelectedArea.minY', index=3,
      number=4, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=336,
  serialized_end=406,
)


_MAINTAINVISION = _descriptor.Descriptor(
  name='MaintainVision',
  full_name='ZSS.Protocol.MaintainVision',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='lastTouch', full_name='ZSS.Protocol.MaintainVision.lastTouch', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='lastTouchTeam', full_name='ZSS.Protocol.MaintainVision.lastTouchTeam', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='processMsg', full_name='ZSS.Protocol.MaintainVision.processMsg', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='maintain', full_name='ZSS.Protocol.MaintainVision.maintain', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='balls', full_name='ZSS.Protocol.MaintainVision.balls', index=4,
      number=5, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=409,
  serialized_end=601,
)


_TEAMROBOTMSG = _descriptor.Descriptor(
  name='TeamRobotMsg',
  full_name='ZSS.Protocol.TeamRobotMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='robot', full_name='ZSS.Protocol.TeamRobotMsg.robot', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=603,
  serialized_end=657,
)


_ROBOT4REC = _descriptor.Descriptor(
  name='Robot4Rec',
  full_name='ZSS.Protocol.Robot4Rec',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='posX', full_name='ZSS.Protocol.Robot4Rec.posX', index=0,
      number=1, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='posY', full_name='ZSS.Protocol.Robot4Rec.posY', index=1,
      number=2, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='angle', full_name='ZSS.Protocol.Robot4Rec.angle', index=2,
      number=3, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='valid', full_name='ZSS.Protocol.Robot4Rec.valid', index=3,
      number=4, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='imuDir', full_name='ZSS.Protocol.Robot4Rec.imuDir', index=4,
      number=5, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='imucleaned', full_name='ZSS.Protocol.Robot4Rec.imucleaned', index=5,
      number=6, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='battery', full_name='ZSS.Protocol.Robot4Rec.battery', index=6,
      number=7, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='capacitance', full_name='ZSS.Protocol.Robot4Rec.capacitance', index=7,
      number=8, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='infrared', full_name='ZSS.Protocol.Robot4Rec.infrared', index=8,
      number=9, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=660,
  serialized_end=821,
)


_BALLS4REC = _descriptor.Descriptor(
  name='Balls4Rec',
  full_name='ZSS.Protocol.Balls4Rec',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='size', full_name='ZSS.Protocol.Balls4Rec.size', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ball', full_name='ZSS.Protocol.Balls4Rec.ball', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='valid', full_name='ZSS.Protocol.Balls4Rec.valid', index=2,
      number=3, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=823,
  serialized_end=898,
)

_RECMESSAGES.fields_by_name['recMsgs'].message_type = _RECMESSAGE
_RECMESSAGE.fields_by_name['selectedArea'].message_type = _SELECTEDAREA
_RECMESSAGE.fields_by_name['maintainVision'].message_type = _MAINTAINVISION
_RECMESSAGE.fields_by_name['debugMsgs'].message_type = zss__debug__pb2._DEBUG_MSGS
_RECMESSAGE.fields_by_name['athenaDebugMsgs'].message_type = zss__debug__pb2._DEBUG_MSGS
_MAINTAINVISION.fields_by_name['processMsg'].message_type = _TEAMROBOTMSG
_MAINTAINVISION.fields_by_name['maintain'].message_type = _TEAMROBOTMSG
_MAINTAINVISION.fields_by_name['balls'].message_type = _BALLS4REC
_TEAMROBOTMSG.fields_by_name['robot'].message_type = _ROBOT4REC
_BALLS4REC.fields_by_name['ball'].message_type = zss__debug__pb2._POINT
DESCRIPTOR.message_types_by_name['RecMessages'] = _RECMESSAGES
DESCRIPTOR.message_types_by_name['RecMessage'] = _RECMESSAGE
DESCRIPTOR.message_types_by_name['SelectedArea'] = _SELECTEDAREA
DESCRIPTOR.message_types_by_name['MaintainVision'] = _MAINTAINVISION
DESCRIPTOR.message_types_by_name['TeamRobotMsg'] = _TEAMROBOTMSG
DESCRIPTOR.message_types_by_name['Robot4Rec'] = _ROBOT4REC
DESCRIPTOR.message_types_by_name['Balls4Rec'] = _BALLS4REC
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RecMessages = _reflection.GeneratedProtocolMessageType('RecMessages', (_message.Message,), {
  'DESCRIPTOR' : _RECMESSAGES,
  '__module__' : 'zss_rec_pb2'
  # @@protoc_insertion_point(class_scope:ZSS.Protocol.RecMessages)
  })
_sym_db.RegisterMessage(RecMessages)

RecMessage = _reflection.GeneratedProtocolMessageType('RecMessage', (_message.Message,), {
  'DESCRIPTOR' : _RECMESSAGE,
  '__module__' : 'zss_rec_pb2'
  # @@protoc_insertion_point(class_scope:ZSS.Protocol.RecMessage)
  })
_sym_db.RegisterMessage(RecMessage)

SelectedArea = _reflection.GeneratedProtocolMessageType('SelectedArea', (_message.Message,), {
  'DESCRIPTOR' : _SELECTEDAREA,
  '__module__' : 'zss_rec_pb2'
  # @@protoc_insertion_point(class_scope:ZSS.Protocol.SelectedArea)
  })
_sym_db.RegisterMessage(SelectedArea)

MaintainVision = _reflection.GeneratedProtocolMessageType('MaintainVision', (_message.Message,), {
  'DESCRIPTOR' : _MAINTAINVISION,
  '__module__' : 'zss_rec_pb2'
  # @@protoc_insertion_point(class_scope:ZSS.Protocol.MaintainVision)
  })
_sym_db.RegisterMessage(MaintainVision)

TeamRobotMsg = _reflection.GeneratedProtocolMessageType('TeamRobotMsg', (_message.Message,), {
  'DESCRIPTOR' : _TEAMROBOTMSG,
  '__module__' : 'zss_rec_pb2'
  # @@protoc_insertion_point(class_scope:ZSS.Protocol.TeamRobotMsg)
  })
_sym_db.RegisterMessage(TeamRobotMsg)

Robot4Rec = _reflection.GeneratedProtocolMessageType('Robot4Rec', (_message.Message,), {
  'DESCRIPTOR' : _ROBOT4REC,
  '__module__' : 'zss_rec_pb2'
  # @@protoc_insertion_point(class_scope:ZSS.Protocol.Robot4Rec)
  })
_sym_db.RegisterMessage(Robot4Rec)

Balls4Rec = _reflection.GeneratedProtocolMessageType('Balls4Rec', (_message.Message,), {
  'DESCRIPTOR' : _BALLS4REC,
  '__module__' : 'zss_rec_pb2'
  # @@protoc_insertion_point(class_scope:ZSS.Protocol.Balls4Rec)
  })
_sym_db.RegisterMessage(Balls4Rec)


# @@protoc_insertion_point(module_scope)
